baseurl = "http://lyckade.github.io/"
languageCode = "de"
title = "Go lycka go"
canonifyurls = true
MetaDataFormat = "toml"
theme = "ghostwriter"
paginate = 10
pygmentsuseclasses = true

disqusShortname = "lyckade"

[author]
    name = "Andreas Schröpfer"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

	
[params]
github = "http://github.com/lyckade"
gravatarHash = "7aa00e82e4289784cbbd55510b28d75d"
rss = true
theme = "theme-base-0d"
tagline = "Go lycka go"
